CREATE TABLE IF NOT EXISTS comics (
    id INT PRIMARY KEY  NOT NULL,
    digitalId INT,
    title VARCHAR,
    issueNumber VARCHAR,
    variantDescription VARCHAR,
    description VARCHAR,
    modified VARCHAR,
    isbn VARCHAR,
    upc VARCHAR,
    diamondCode VARCHAR,
    ean VARCHAR,
    issn VARCHAR,
    format VARCHAR,
    pageCount VARCHAR,
    text VARCHAR,
    Objects VARCHAR,
    resourceURI VARCHAR,
    urls VARCHAR,
    series VARCHAR,
    variants VARCHAR,
    collections VARCHAR,
    collectedIssues VARCHAR,
    dates VARCHAR,
    prices VARCHAR,
    thumbnail VARCHAR,
    images VARCHAR,
    creators VARCHAR,
    characters VARCHAR,
    stor VARCHAR,
    ies VARCHAR,
    events VARCHAR
    );