DROP TABLE if exists comics;

CREATE TABLE comics (    
    id INT  NOT NULL,
    digitalId INT,
    title VARCHAR,
    issueNumber VARCHAR,
    variantDescription VARCHAR,
    description VARCHAR,
    modified VARCHAR,
    isbn VARCHAR,
    upc VARCHAR,
    diamondCode VARCHAR,
    ean VARCHAR,
    issn VARCHAR,
    format VARCHAR,
    pageCount VARCHAR,
    textObjects VARCHAR,
    resourceURI VARCHAR,
    urls VARCHAR,
    series VARCHAR,
    variants VARCHAR,
    collections VARCHAR,
    collectedIssues VARCHAR,
    dates VARCHAR,
    prices VARCHAR,
    thumbnail VARCHAR,
    images VARCHAR,
    creators VARCHAR,
    characters VARCHAR,
    stories VARCHAR,
    events VARCHAR
    );